import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "Prevalence of cocaine in the EU population",
  "subtitle": "Share of cocaine use in the European Union in 2024 among the European population aged 15 to 64 (or most recent data available)",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nAustria,AT,0.015,TRUE,\"Survey year: 2022\",,,,,,,,\nBelgium,BE,0.016,TRUE,\"Survey year: 2024\",,,,,,,,\nBulgaria,BG,0.014,TRUE,\"Survey year: 2024\",,,,,,,,\nCyprus,CY,0.007,TRUE,\"Survey year: 2022\",,,,,,,,\nCzechia,CZ,0.004,TRUE,\"Survey year: 2023\",,,,,,,,\nGermany,DE,0.011,TRUE,\"Survey year: 2024\",,,,,,,,\nDenmark,DK,0.021,TRUE,\"Survey year: 2023\",,,,,,,,\nEstonia,EE,0.021,TRUE,\"Survey year: 2023\",,,,,,,,\nGreece,EL,0.004,TRUE,\"Survey year: 2015\",,,,,,,,\nSpain,ES,0.025,TRUE,\"Survey year: 2024\",,,,,,,,\nFinland,FI,0.016,TRUE,\"Survey year: 2022\",,,,,,,,\nFrance,FR,0.027,TRUE,\"Survey year: 2023\",,,,,,,,\nCroatia,HR,0.008,TRUE,\"Survey year: 2015\",,,,,,,,\nItaly,IT,0.014,TRUE,\"Survey year: 2022\",,,,,,,,\nLithuania,LT,0.006,TRUE,\"Survey year: 2021\",,,,,,,,\nLuxembourg,LU,0.005,TRUE,\"Survey year: 2019\",,,,,,,,\nLatvia,LV,0.013,TRUE,\"Survey year: 2020\",,,,,,,,\nMalta,MT,0.003,TRUE,\"Survey year: 2023\",,,,,,,,\nNetherlands,NL,0.029,TRUE,\"Survey year: 2024\",,,,,,,,\nPoland,PL,0.004,TRUE,\"Survey year: 2024\",,,,,,,,\nPortugal,PT,0.002,TRUE,\"Survey year: 2022\",,,,,,,,\nRomania,RO,0.008,TRUE,\"Survey year: 2024\",,,,,,,,\nSweden,SE,0.013,TRUE,\"Survey year: 2021\",,,,,,,,\nSlovenia,SI,0.009,TRUE,\"Survey year: 2023\",,,,,,,,\nSlovakia,SK,0.005,TRUE,\"Survey year: 2023\",,,,,,,,\nHungary,HU,0.001,TRUE,\"Survey year: 2023\",,,,,,,,\nIreland,IE,0.024,TRUE,\"Survey year: 2023\",,,,,,,,",
  "parsedData": [
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.015,
      "extraInfo": true,
      "text_content": "Survey year: 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.016,
      "extraInfo": true,
      "text_content": "Survey year: 2024",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.014,
      "extraInfo": true,
      "text_content": "Survey year: 2024",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": 0.007,
      "extraInfo": true,
      "text_content": "Survey year: 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.004,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.011,
      "extraInfo": true,
      "text_content": "Survey year: 2024",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.021,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.021,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0.004,
      "extraInfo": true,
      "text_content": "Survey year: 2015",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.025,
      "extraInfo": true,
      "text_content": "Survey year: 2024",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.016,
      "extraInfo": true,
      "text_content": "Survey year: 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.027,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": 0.008,
      "extraInfo": true,
      "text_content": "Survey year: 2015",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.014,
      "extraInfo": true,
      "text_content": "Survey year: 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": 0.006,
      "extraInfo": true,
      "text_content": "Survey year: 2021",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.005,
      "extraInfo": true,
      "text_content": "Survey year: 2019",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.013,
      "extraInfo": true,
      "text_content": "Survey year: 2020",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": 0.003,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.029,
      "extraInfo": true,
      "text_content": "Survey year: 2024",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": 0.004,
      "extraInfo": true,
      "text_content": "Survey year: 2024",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": 0.002,
      "extraInfo": true,
      "text_content": "Survey year: 2022",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.008,
      "extraInfo": true,
      "text_content": "Survey year: 2024",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.013,
      "extraInfo": true,
      "text_content": "Survey year: 2021",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.009,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.005,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": 0.001,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": 0.024,
      "extraInfo": true,
      "text_content": "Survey year: 2023",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "European Union Drug Agency",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "Survey data for Greece and Croatia are from 2015, while data for Luxembourg are from 2019.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://d9www.euda.europa.eu/publications/european-drug-report/2026/cocaine_en#edr26-cocaine-prevalence",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": true,
  "customUnitLabel": "of adults",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "Prevalence of cocaine in the EU population",
    "subtitle": "Share of cocaine use in the European Union in 2024 among the European population aged 15 to 64 (or most recent data available)",
    "textNoteDescription": "Note",
    "textNote": "Survey data for Greece and Croatia are from 2015, while data for Luxembourg are from 2019.",
    "textSourceDescription": "Source",
    "textSource": "European Union Drug Agency",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here",
    "extraInfo_AT": "Survey year: 2022",
    "extraInfo_BE": "Survey year: 2024",
    "extraInfo_BG": "Survey year: 2024",
    "extraInfo_CY": "Survey year: 2022",
    "extraInfo_CZ": "Survey year: 2023",
    "extraInfo_DE": "Survey year: 2024",
    "extraInfo_DK": "Survey year: 2023",
    "extraInfo_EE": "Survey year: 2023",
    "extraInfo_EL": "Survey year: 2015",
    "extraInfo_ES": "Survey year: 2024",
    "extraInfo_FI": "Survey year: 2022",
    "extraInfo_FR": "Survey year: 2023",
    "extraInfo_HR": "Survey year: 2015",
    "extraInfo_IT": "Survey year: 2022",
    "extraInfo_LT": "Survey year: 2021",
    "extraInfo_LU": "Survey year: 2019",
    "extraInfo_LV": "Survey year: 2020",
    "extraInfo_MT": "Survey year: 2023",
    "extraInfo_NL": "Survey year: 2024",
    "extraInfo_PL": "Survey year: 2024",
    "extraInfo_PT": "Survey year: 2022",
    "extraInfo_RO": "Survey year: 2024",
    "extraInfo_SE": "Survey year: 2021",
    "extraInfo_SI": "Survey year: 2023",
    "extraInfo_SK": "Survey year: 2023",
    "extraInfo_HU": "Survey year: 2023",
    "extraInfo_IE": "Survey year: 2023"
  },
  "clusters": [],
  "colorScale": null,
  "extraInfo_AT": "Survey year: 2022",
  "extraInfo_BE": "Survey year: 2024",
  "extraInfo_BG": "Survey year: 2024",
  "extraInfo_CY": "Survey year: 2022",
  "extraInfo_CZ": "Survey year: 2023",
  "extraInfo_DE": "Survey year: 2024",
  "extraInfo_DK": "Survey year: 2023",
  "extraInfo_EE": "Survey year: 2023",
  "extraInfo_EL": "Survey year: 2015",
  "extraInfo_ES": "Survey year: 2024",
  "extraInfo_FI": "Survey year: 2022",
  "extraInfo_FR": "Survey year: 2023",
  "extraInfo_HR": "Survey year: 2015",
  "extraInfo_IT": "Survey year: 2022",
  "extraInfo_LT": "Survey year: 2021",
  "extraInfo_LU": "Survey year: 2019",
  "extraInfo_LV": "Survey year: 2020",
  "extraInfo_MT": "Survey year: 2023",
  "extraInfo_NL": "Survey year: 2024",
  "extraInfo_PL": "Survey year: 2024",
  "extraInfo_PT": "Survey year: 2022",
  "extraInfo_RO": "Survey year: 2024",
  "extraInfo_SE": "Survey year: 2021",
  "extraInfo_SI": "Survey year: 2023",
  "extraInfo_SK": "Survey year: 2023",
  "extraInfo_HU": "Survey year: 2023",
  "extraInfo_IE": "Survey year: 2023"
});